ALTER TYPE "SyncStatus" ADD VALUE 'PARTIAL';
ALTER TYPE "IntegrationJobStatus" ADD VALUE 'PARTIAL';
ALTER TYPE "IntegrationJobStatus" ADD VALUE 'SKIPPED';
ALTER TABLE "SyncCheckpoint" ADD COLUMN "failed" INTEGER NOT NULL DEFAULT 0;
